language: php
cache:
  directories:
    - vendor
services:
  - mysql-server
addons:
  hosts:
    - mysql-server
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
before_install:
  - sudo apt-get install -y jq
install:
  - make
before_script:
  - mysql -uroot -e "CREATE DATABASE IF NOT EXISTS test DEFAULT CHARSET=utf8"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON test.* TO 'testuser'@'localhost' IDENTIFIED BY 'testpass'"
script:
  - make test
  - make lint
