version: "3.7"
services:
  app:
    build: ./docker/
    working_dir: /srv
    volumes:
      - .:/srv/
    links:
      - mysql-server
      - sftp-server
    depends_on:
        - mysql-server
        - sftp-server
  mysql-server:
    image: circleci/mysql:5.7-ram
    shm_size: '256mb'
  sftp-server:
    image: atmoz/sftp
    command: foo:pass:1001
