version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-composer-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-composer-

      - run: docker-compose up -d
      - run: docker exec -it php-exercise make

      - save_cache:
          paths:
            - ./vendor
          key: v1-composer-{{ checksum "composer.json" }}

      - run: docker exec -it php-exercise make test
workflows:
  version: 2
  build:
    jobs:
      - build
