version: '3'
services:
  app:
    container_name: php-exercise
    image: php
    volumes:
      - $PWD/..:/srv/
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
