version: '3'
services:
  app:
    container_name: php-exercise
    build: ./
    volumes:
      - $PWD/..:/srv/
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
    links:
      - mysql-server
    ports:
      - 8080:8080
  mysql-server:
    image: circleci/mysql:5.7
