name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: env | sort

      - run: docker-compose up -d
      - run: docker-compose ps

      - run: docker-compose run app make
      - run: docker-compose run app make test
