name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - run: env | sort

      - uses: satackey/action-docker-layer-caching@v0.0.11
      - run: make compose/up
      - run: docker compose ps

      - run: docker compose run --user root app chown -R circleci:circleci /srv
      - run: docker compose run app make
      - run: docker compose run app make test
